### ISSUE TITLE
`NamedRouteRedirectStyle` Lint

### ISSUE THREAD

**Issue by loganhenson** [tighten/tlint#150]
prefer `redirect()->route('named-route')` to `redirect(route('named-route'))` and `redirect()->to(route('named-route'))`

![image](https://user-images.githubusercontent.com/2792946/82068801-1b927580-9698-11ea-8a6d-497289190a43.png)

**Comment by driftingly** [comment]
In the future we may want to look at adding support for L9 `to_route('named-route')` over `redirect()->route('named-route')`.
