### ISSUE TITLE
`NoGroupUseStatements` Lint

### ISSUE THREAD

**Issue by loganhenson** [tighten/tlint#161]
Prefer inline use statements over grouped use statements

**Comment by bakerkretzmar** [comment]
Does this mean

```php
class Foo
{
    use Bar;
    use Baz;
}
```

instead of

```php
class Foo
{
    use Bar, Baz;
}
```

or

```php
use Foo\Bar;
use Foo\Baz;
```

instead of

```php
use Foo\{
    Bar;
    Baz;
}
```

or both?

**Comment by driftingly** [comment]
The linting of group use with traits is handled in [PRS-12](https://www.php-fig.org/psr/psr-12/) section 4.2:

> Each individual trait that is imported into a class MUST be included one-per-line and each inclusion MUST have its own use import statement.

This linter can be set up to lint against [Group use import statements](https://www.php.net/manual/en/language.namespaces.importing.php#language.namespaces.importing.group).

Preferring this:
```php
use some\namespace\ClassA;
use some\namespace\ClassB;
use some\namespace\ClassC as C;

use function some\namespace\fn_a;
use function some\namespace\fn_b;
use function some\namespace\fn_c;

use const some\namespace\ConstA;
use const some\namespace\ConstB;
use const some\namespace\ConstC;
```

Over this:
```php
use some\namespace\{ClassA, ClassB, ClassC as C};
use function some\namespace\{fn_a, fn_b, fn_c};
use const some\namespace\{ConstA, ConstB, ConstC};
```
