### ISSUE TITLE
PhpParser Notice

### ISSUE THREAD

**Issue by jcorrego** [tighten/tlint#167]
Im getting this Notice
```Notice: Undefined property: PhpParser\Node\Expr\FuncCall::$var in tightenco/tlint/src/Concerns/IdentifiesModelMethodTypes.php on line 107```

This was after upgrading to Laravel 8, but i dont see anything related to that.

**Comment by jcorrego** [comment]
Update: The notice dissapears if i comment out `Linters\ModelMethodOrder::class` linter...

**Comment by Gummibeer** [comment]
Assign it to me - I have the same problem in one of our projects, I've also found the solution and have introduced the error. 🤦‍♂️

**Comment by Gummibeer** [comment]
@jcorrego I would be thankful if you could share the model code in #174 - detailed guidelines are listed in the linked issue.
This will help me preventing such issues in the future by testing with real models.
