### ISSUE TITLE
README link to Handbook 404s

### ISSUE THREAD

**Issue by runofthemill** [tighten/tlint#168]
Hi there!

Perhaps the handbook repo is not public, but the link here in the README under **General PHP** 404s, as does trying to navigate to `https://github.com/tighten/handbook`.

> Class "things" should follow the ordering presented in the [handbook](https://github.com/tighten/handbook/tree/master/coding-standards/php#classesobjects). `ClassThingsOrder`

Cheers :)

**Comment by mattstauffer** [comment]
Thanks! Updated.
