### ISSUE TITLE
Tighten preset vs Laravel preset

### ISSUE THREAD

**Issue by RalphMRivera** [tighten/tlint#173]
Does the `tighten` preset include the rules of the `laravel` preset with additional lints?

**Comment by loganhenson** [comment]
@RalphMRivera The `tighten` preset is not a superset of the `laravel` preset no, it has lots of _opinions_ ™️ from tighten people in it.

You can see exactly what is included in each here: https://github.com/tighten/tlint/tree/b41438e90fef70e8e409e14908b640a3c61e9c9a/src/Presets
