### ISSUE TITLE
Doc block triggering OneLineBetweenClassVisibilityChanges lint

### ISSUE THREAD

**Issue by delta1186** [tighten/tlint#196]
In the process of cleaning up an existing project, I ran into an issue with the OneLineBetweenClassVisibilityChanges linter where it does not appear to play nicely with doc blocks. If I remove the doc block the linter is not triggered.  

And don't worry I know my properties are in the wrong order. :)  

I can make an attempt to fix this issue if you would like.  

Also, I am going to submit a secondary PR to add the AlphabeticalImports linter to the Laravel preset.

![image](https://user-images.githubusercontent.com/421307/96305700-e9c56800-0fc3-11eb-8879-99fb720e98f2.png)

![image](https://user-images.githubusercontent.com/421307/96305648-d6b29800-0fc3-11eb-9c32-4afc3783b2eb.png)

**Comment by loganhenson** [comment]
Ah interesting re: docblock.

re: `AlphabeticalImports`, The last I looked the convention in the Laravel codebase was to order imports by length, has that changed?

**Comment by delta1186** [comment]
https://gist.github.com/laravel-shift/cab527923ed2a109dda047b97d53c200#file-php_cs-laravel-php-L87

I am going off of Laravel Shift's php-cs-fixer config.  Line 87

**Comment by delta1186** [comment]
Here is a snip from a class in the laravel/framework repo.  
![image](https://user-images.githubusercontent.com/421307/96306870-25f9c800-0fc6-11eb-9d12-62c197706155.png)

Here is a snip from laravel/laravel repo
![image](https://user-images.githubusercontent.com/421307/96306979-6b1dfa00-0fc6-11eb-9a5b-469188f7d03e.png)

**Comment by delta1186** [comment]
@loganhenson just wanted to circle the wagon to make sure you did not have any questions or concerns.  Thanks!

**Comment by loganhenson** [comment]
@delta1186 thanks! Tagged 👍
