### ISSUE TITLE
Syntax error, unexpected T_NAME_RELATIVE

### ISSUE THREAD

**Issue by andersespedalen** [tighten/tlint#199]
In Laravel 7, I experience the same error on nearly all files in app/ 

```
Lints for /var/www/payapi/app/Console/Kernel.php
============
! Syntax error, unexpected T_NAME_RELATIVE
3 : `namespace app\Console;`
```

The error triggers on the namespace declaration at the top of the file:
`namespace app\Console;`

I can't find any reference to this constant **T_NAME_RELATIVE**

A possible cause could be that I have changed App->app in my directory- and namespaces-

**Comment by Gummibeer** [comment]
Are you running on PHP8? If so this could be the reason.
https://wiki.php.net/rfc/namespaced_names_as_token
Your lowercased `app` could conflict with the global `app()` function.

**Comment by andersespedalen** [comment]
PHP7. 
Not sure why, but it worked when I moved back to first letter uppercase in the 'App' namespace
