### ISSUE TITLE
`DeprecatedDatesAttribute` Lint

### ISSUE THREAD

**Issue by Gummibeer** [tighten/tlint#201]
In Laravel 8 the `$dates` property was deprecated in favor of `$casts`.
https://github.com/illuminate/database/blob/0073d465400dd893cb4c042588d1ac308f651a33/Eloquent/Concerns/HasAttributes.php#L89-L96

There should be a linter that warns about the usage of `$dates`.

**Comment by loganhenson** [comment]
Good catch!

**Comment by Gummibeer** [comment]
If anyone starts working on this please write/assign - otherwise I will possibly have time for it end of the week.

**Comment by loganhenson** [comment]
@bakerkretzmar Think this should be added to the Tighten & Laravel presets? I think that probably makes sense
