### ISSUE TITLE
Packagist Update

### ISSUE THREAD

**Issue by delta1186** [tighten/tlint#203]
@loganhenson I was running tlint on my project today and was getting lints for the issue I fixed.  I ran composer g update just to be sure I was on 5.0.6.  It was still showing lints.  I looked at the OneLineBetweenClassVis... file in my global folder and noticed the PR I submitted was not included.  Not sure if the tag is pushing changes to Packagist? Or am I doing something wrong?

And for reference I did update on the 16th when you tagged 5.0.6.  My files modified date is 10/16/20 12:41 PM.

**Comment by mattstauffer** [comment]
@delta1186 I'm seeing some commits since the last tag, some of which have your picture on them :)

https://github.com/tighten/tlint/compare/v5.0.6...master

I'll ping Logan to push a tag.

**Comment by loganhenson** [comment]
tagged `v5.0.7` 👍
