### ISSUE TITLE
Drop `PureRestControllers` & `ModelMethodOrder` lints

### ISSUE THREAD

**Issue by loganhenson** [tighten/tlint#223]

**Comment by mattstauffer** [comment]
Should we maybe keep them but just remove them from the tighten preset?

**Comment by loganhenson** [comment]
Ah, I see they are in the Laravel preset, didn't realize that. I suppose we should keep them then 😅

**Comment by mattstauffer** [comment]
Huh. I mean,  neither of those are really Laravel specified either. I think we should drop them there too, no?

**Comment by driftingly** [comment]
Closed by #231
