### ISSUE TITLE
Add option to run tlint without the formatter 

### ISSUE THREAD

**Issue by Wulfheart** [tighten/tlint#244]
Sometimes it is not desired to run formatters. Therefore it would be nice to have an option to disable them.

**Comment by Wulfheart** [comment]
Ah, just reading would have been better. 😓  There is a command for it. But this command is not displayed in the help.

**Comment by loganhenson** [comment]
Ah, yep haha. The formatter is considered "beta" so is not technically stable, they are kind of an opt in feature. Perhaps we should add them to the help simply for discoverability though!
