### ISSUE TITLE
Feature Request: Add Formatters for all Linters

### ISSUE THREAD

**Issue by mattstauffer** [tighten/tlint#250]
This is especially true for any linters that are present in the Tighten lint preset that are not in sync with how a new Laravel app comes styled.

What I'd love to do is run this:

```php
laravel new project
cd project
tlint format
```

And then just have it perfectly in sync with the Tlint Tighten preset.

**Progress** (added by @bakerkretzmar, updated by @driftingly):

Here is the progress on the rest:
- [x] ArrayParametersOverViewWith.php
- [x] FullyQualifiedFacades.php
- [x] MailableMethodsInBuild.php
- [x] NoDatesPropertyOnModels.php
- [x] NoDocBlocksForMigrationUpDown.php
- [x] NoLeadingSlashesOnRoutePaths.php
- [x] NoSpaceAfterBladeDirectives.php
- [x] OneLineBetweenClassVisibilityChanges.php
- [x] RemoveLeadingSlashNamespaces.php
- [x] RequestHelperFunctionWherePossible.php
- [x] RequestValidation.php
- [x] SpaceAfterBladeDirectives.php
- [x] SpacesAroundBladeRenderContent.php
- [x] UseAuthHelperOverFacade.php

We cannot reliably format issues found by these linters:
 - `ApplyMiddlewareInRoutes` - No way to reliably update the route files.
 - `PureRestControllers` - No way to refactor other methods.
 - `NoRequestAll` - No way to know what is being sent.
 - `NoJsonDirective` - Multiple replacement methods, depending on context.
 - `QualifiedNamesOnlyForClassName` - Cannot reliably add use statements, issues around namespaces and renaming on collisions.

**Comment by driftingly** [comment]
All linters now have a corresponding formatter where we are able (PRs pending).

The recommendation moving forward will be to use TLint as part of Duster, as it will provide the most complete code styling.

**Comment by mattstauffer** [comment]
Amazing. Thank you so much, @driftingly!!!
