### ISSUE TITLE
`ImportFacades` formatter doesn't work on files with a namespace

### ISSUE THREAD

**Issue by bakerkretzmar** [tighten/tlint#252]
Big 🤦🏻 moment for me—the `ImportFacades` formatter just _stops_ when it finds a namespace, which makes it basically useless.

I _think_ in files with namespaces, statements/nodes following the namespace are _children_ of the namespace, so we may just have to check for namespaces and loop over their children instead.

We should have tests with namespaces too 😅

**Comment by driftingly** [comment]
Related to #251 

We'll be looking into:

- updating `ImportFacades` to describe exactly what it does.
- adding a new linter to do what this linter is supposed to do
- fixing the formatter (possible creating a new one to match new linter)
  - there is an issue with namespace files, loop through child nodes when using namespace.

**Testing**

Duplicate the current tests and add namespaces.
