### ISSUE TITLE
`FatArrowSpace` linter/formatter

### ISSUE THREAD

**Issue by driftingly** [tighten/tlint#269]
The consensus at Tighten and in the Laravel community is to include a spaces after `fn`:

```php
fn () =>
```

Example from [Laravel Docs](https://laravel.com/docs/8.x/collections#method-takeUntilTimeout)

```php
$sorted = $collection->sortBy([
    fn ($a, $b) => $a['name'] <=> $b['name'],
    fn ($a, $b) => $b['age'] <=> $a['age'],
]);
```

**Comment by bakerkretzmar** [comment]
This would be nice! Just a note that `php-cs-fixer` does fix this by default (the `function_declaration` rule).

**Comment by driftingly** [comment]
This will be covered by https://github.com/tighten/tighten-coding-standard/pull/9
