### ISSUE TITLE
Customizable paths in config

### ISSUE THREAD

**Issue by ecrmnn** [tighten/tlint#287]
Hey!
We use TLint in multiple projects and love it! Great job! 👏

In some of our apps we have a different app structure.
We might have "Modules" both the root directory or within the app directory.
These "Modules" contains controllers and other logic.

We're unable to lint these files due to how the path is being set.
E.g. LintsControllers, https://github.com/tighten/tlint/blob/main/src/Linters/Concerns/LintsControllers.php

How could TLint allow a preset or config to customize paths that override traits?
Is this even of interest to add to the package?
We would be happy to make a PR, but how would you like it solved?
Or should we simply fork it and roll our own solution?

**Comment by driftingly** [comment]
@ecrmnn will PR #288 work for you?

**Comment by ecrmnn** [comment]
Thanks @driftingly 

I'm pretty sure this solves our problem. Thanks a lot!

We've written a few custom rules as well, do you think it's best to keep them in our own separate package or would you like us to make PRs to TLint?

**Comment by driftingly** [comment]
@ecrmnn This has been tagged v6.3.0.

For PRs, yes please, PRs are welcomed.  Just keep in mind they may not get merged in (the tool is fairly opinionated), but it would be helpful to see what extra functionality you needed.  There's a bit of a shift coming with the 7.0 release.  This tool will leave a lot of sniffing/formatting to another tool where that tool is able: https://github.com/tighten/tlint/pull/284

**Comment by ecrmnn** [comment]
We're using TLint in combination with PHP CS Fixer since we feel it lacks important rules. Just take NoCompact as an example, there isn't any equivalent in PHP CS Fixer as I know of.

What are you planning on removing?

Would be good to know so we don't invest time in a package that is going away or changed drastically.

**Comment by driftingly** [comment]
We are removing lints and formatters that are covered by those other tools (Sniffer and Fixer) and focusing on what those tools cannot do.
