### ISSUE TITLE
[Idea] Disallow mass assignment rule

### ISSUE THREAD

**Issue by Wulfheart** [tighten/tlint#292]
[Some Laravel code guides ](https://handbook.interaction-design.org/development/library/back-end/conventions--laravel.html#don-t-use-mass-assignment) discourage the usage of mass assignment. Would you be willing to merge a rule which lints the use of it?

**Comment by bakerkretzmar** [comment]
Personally, no. I much prefer mass assignment with `create()` and `update()` over the individual property assignment in that example, and we already have a rule that lints `$request->all()` to encourage being explicit about passing around request input. Open to hearing what others think though.

**Comment by driftingly** [comment]
I agree with @bakerkretzmar here, thanks for the suggestion @Wulfheart.
This can always be added to a custom preset for your own use 👍
