### ISSUE TITLE
Look into bundling as PHAR

### ISSUE THREAD

**Issue by driftingly** [tighten/tlint#327]
I'm wondering if bundling TLint as a PHAR would reduce our testing overhead around symfony:

```
 symfony:
  [
    [4, "^4.4.30", "^4.4.20"],
    [5, "^5.3.7", "^5.0.9"],
    [6, "^6.0", "^6.0"],
  ]
```

Would this allow us to use symfony components without worrying about the included version in the project TLint is being used on?

Not sure how this change would affect the IDE plugins.

**Comment by bakerkretzmar** [comment]
Interesting! I have no idea what effect that would have. I think most of the motivation behind supporting that many versions was to support older versions of PHP... that would still matter with a PHAR right?
