### ISSUE TITLE
Ability to silence "LGTM!" messages

### ISSUE THREAD

**Issue by indykoning** [tighten/tlint#356]
I'm automating running TLint using Duster with https://github.com/indykoning/grumphp-duster
With small changes this task creates a lot of spam in the form of `LGTM!` messages

This is what it looks like with ~20 files
![image](https://github.com/tighten/tlint/assets/15870933/934d1e1d-4f93-4357-8fb0-3dfa5a229ae2)
Which blows up with more files, pushing any useful feedback away.

It would be really nice to have an option to configure where the positive output is silenced and only things that need to be fixed get outputted

**Comment by patrick-vlt** [comment]
What does this LGTM! even mean? Im trying to lint a blade file and all I get is one LGTM error, thats it.

**Comment by driftingly** [comment]
I'm updating Duster to prevent this output: 
https://github.com/tighten/duster/pull/167
